### PR TITLE
README: Updating readme

### PR DESCRIPTION
**Pull request by shamisp**
Removing gitlab reference and adding list of the known issues.

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by shamisp** [comment]
@tonycurtis please take a look

**Review by tonycurtis — CHANGES_REQUESTED** [review]
should specify Linux kernel?

**Comment by shamisp** [comment]
@tonycurtis added clarification

**Comment by shamisp** [comment]
@tonycurtis good to go ?

**Review by tonycurtis — APPROVED** [review]

**Pull request merged**
