### PR TITLE
Add support for setting the kernel module prefix

### PR DESCRIPTION
**Pull request by shamisp**
Pulling changes from Nathan

### CODE REVIEW

**Comment by shamisp** [comment]
@yosefe please take a look.

**Comment by shamisp** [comment]
@tonycurtis please take a look

**Review by tonycurtis — COMMENTED** [review]
traditionally xpmem has gone into the extra/ sub-directory.  Reason for change?

**Comment by shamisp** [comment]
It does not change existing behavior - it just adds an option to install in different location, which might be desirable.

**Comment by shamisp** [comment]
@tonycurtis - ping

**Review by tonycurtis — APPROVED** [review]
oops, missed this

**Pull request merged**
